### ISSUE TITLE
Python naming convention

### ISSUE THREAD

**Issue by Korusuke** [macports/upt-macports#23]
So the discussion about this also took place during the proposal period but we were not able to get to a conclusion.

| PyPI Name | Center-aligned | Number |
|     :---:      |     :---:      |     :---:      |
| foo   | foo     | 10    |
| foo   | py-foo     | 769    |
| foo   | py-pyfoo     | 1    |
| pyfoo   | py-foo     | 14    |
| ---   | ---     | 30    |

According to the above stats we can see there are inconsistencies in the naming convention of python ports.

Whereas for Perl and Ruby the naming convention is pretty much consistent as the upstream is the same for every port.
This helps in easily automating the packaging process and also provide ease of use.

but in Python, as the upstream are different naming inconsistencies can be seen, it would be nice to follow a naming scheme from now on and it would help in long term maintainability of ports.

Following the pattern of ruby, perl ports we can have the following naming convention:

Upstream Package name: `Foo` 
port name: `py-Foo` (capitalization should be maintained)
port folder name: `py-foo`

I would like to get the view of the community on this and if there is any other convention that we should follow instead?

**Comment by reneeotten** [comment]
There are two other things to consider:
1. (in general) the ```name``` field and the folder name should match (including capitalization and such), otherwise ```port lint``` will complain.

2. In the Python ports we want to be able to use ```PortGroup python 1.0```, which sets automatically ```python.rootname``` to the part after ```py-```<python.rootname> of the ```name``` field. This variable can then be later on in the Portfile used (as you do now in the template) to set the ```distname```, ```master_sites```, ```livecheck``` and such. In order for all of this to work, ```python.rootname``` must be equal to the PyPI name. 

Based on your statistics and the most common use-case in MacPorts I think we should do the following:
1. set ```name``` (and Portfile directory) equal to PyPI.lower() for all ports.

The vast majority of the ports already follows this naming scheme, and we would need to fix the ```foo -->  py-pyfoo``` and ```pyfoo --> py-foo``` occurrences, which are about 15 ports. Additionally, all ports that currently have upper case characters in them will need to be renamed. I am sure there are  others, but we can deal with translating them when we find them (or you can of course actively look for them)... In some cases this will result in ports (re)named as ```py-python-<name>``` (e.g., ```py-python-dateutil``` from ```py-dateutil```), which some people might not like, but there is precedent for this naming scheme as well...

The ports that you have listed as ```foo --> foo``` are most likely not "real" Python libraries, but rather command-line-tools that happen to be written in Python (see the discussion [here](https://github.com/macports/macports-ports/pull/4489#discussion_r288493199)). They probably shouldn't be in the "python" directory, but elsewhere in another primary category; let's not worry about them right now. This is related though to @mojca her request on the mailinglist to possibly add a flag for ```upt``` so that also these ports can be generated (something for later I think).

So in the backend you'll need to change the code to get the "MacPorts package name" and use the same translation when writing out the dependencies as well. Finally, if ```name``` is not equal to PyPI name, then you should set in the ```python.Portfile``` template the ```python.rootname``` field to be equal to the PyPI name.

@jmroot @ryandesign are there any considerations or "implicit MacPorts conventions" that we should take into account here and/or how much backlash will this change give? It's kind of crucial for ```upt``` to be able to work to get the naming scheme sorted out soon-ish.

[Edit: another option is of course to always use ```py-<PyPI_name>``` irrespective of capitalization, but this would require (I think) more changes and my understanding is that MacPort prefers lowercase names]

**Comment by reneeotten** [comment]
for future reference see the feedback on [the mailinglist](https://lists.macports.org/pipermail/macports-dev/2019-June/040812.html)

**Comment by reneeotten** [comment]
for new ports we follow the naming-conventions ```py-<upstream_name>``` including capitalization. See the link above though for some more considerations; therefore, re-opening the issue as not everything is resolved as of yet.

**Comment by reneeotten** [comment]
see also #29 for some more discussion about this, especially regarding the number of ports that would be potentially affected. The "executive" decision for ```upt``` is to use py-<upstream>  (all lowercase) for Python ports as this is most consistent with the current usage in MacPorts and follows also the naming scheme for Perl ports.

**Comment by Korusuke** [comment]
Is there any use of this issue anymore?
